### ISSUE TITLE
Generated Skill Failed with TypeError: object is not a function

### ISSUE THREAD

**Issue by aidanbon** [cameronhunter/generator-alexa-skill#5] opened 2016-03-25 05:39 UTC
Followed the README instruction to generate and "npm run deploy" a HelloWorld Lambda function, and then finished with configuring an Alexa Skill to work with this function at the Alexa Developer portal.

However, when I test the HelloWorld skill, it fails and see the following error at the AWS CloudWatch log:

```
START RequestId: 84fabc9e-f184-11e5-b238-03a3a5a66ffb Version: $LATEST 
2016-03-24T05:51:58.218Z    84fabc9e-f184-11e5-b238-03a3a5a66ffb    TypeError: object is not a function 
END RequestId: 84fabc9e-f184-11e5-b238-03a3a5a66ffb
```

Did I miss something?

**Comment by cameronhunter** [comment] 2016-04-04 04:23
Sorry, a change in how babel handles exporting to commonjs (required for AWS Lambda) was the cause. I've fixed in the most recent version (>= 3.0.0).

Thanks for reporting!

**Closed as completed by cameronhunter** 2016-04-04 04:23 UTC

**Comment by aidanbon** [comment] 2016-04-06 06:07
Thanks @cameronhunter.

However, when I use v3.0.3 of the generator, got the following error at bin/deploy:

```
> bin/deploy --config config/lambda.config.js --package build/package.zip

AWS API request failed. Check your AWS credentials and permissions.
Deployment failed: { [MissingRequiredParameter: Missing required key 'FunctionName' in params]
  message: 'Missing required key \'FunctionName\' in params',
  code: 'MissingRequiredParameter',
  time: Tue Apr 05 2016 21:56:36 GMT-0700 (PDT) }
```

Looks like it is an issue with transpiling config/lambda.config.js. The config object becomes 

```
{
   default: {
        accessKeyId: 'xxx',
         ...
   }
}
```

The extra "default" attribute is not expected by node-aws-lambda, hence failing the deployment.

I think this can be fixed by using the common.js "module.exports =" syntax in config/lambda.config.js, or use the babel-plugin-add-module-exports Babel plugin.

I'll submit a PR with the latter approach for your consideration.

**Comment by cameronhunter** [comment] 2016-04-06 15:29
Ah, same issue with webpack. I've been using npm run package and uploading
manually if that's helpful (until it's fixed)?

Thanks for the report!
